OSC/ood-ansible

defaults/main.yml, handlers/main.yml, molecule/default/playbook.yml, molecule/default/tests/test_custom.py, molecule/default/tests/test_default.py, molecule/default/tests/test_instance.py, tasks/configure.yml
Apache's ood-portal.conf is currently managed exclusively by ansible
template, without the possibility of using ood-portal-generator
This commit add the update ood portal handler to generate
ood-portal.conf based on ood-portal.yml
* Add httpd htcacheclean handler
* Add ignore error com portal generation
=> Add support for ood-portal-generator

tasks/configure.yml, tasks/main.yml
I kept failing [at this](https://github.com/OSC/ood-ansible/blob/ce3cde9d16e12c7ec624cdd316dfabfabc9b0063/tasks/configure.yml#L67) task to start apache when I first install.  Turns out you need to be root to start the httpd service. 
This is a small refactor to just move all those `become: true` statements to the top level configure because _every single task_ had one, so why not just apply to the top level configure.
=> all of configure needs to become

README.md, molecule/default/playbook.yml, molecule/default/tests/test_custom.py, tasks/cluster.yml, tasks/clusters.yml, tasks/main.yml
Previously we could write a single cluster config file.
This commit allows users to set a dict of clusters where a cluster file
will be created for each item.
=> Write multiple clusters file #28

.gitignore, .travis.yml, README.md, defaults/main.yml, handlers/main.yml, molecule/default/playbook.yml, tests/extra_vars.json
As we march to a 1.0 release in Galaxy, I feel like now is the time to solidify these entries as the defaults.
This was originally developed for non-RPM based systems, but I feel like that's the corner case, and indeed, automation targeting RPM based systems is the more common case and defaults should reflect that. 
Using the ood-portal-generator also gets flipped to be default.  We can keep the template, and even later allow users to specify their own, but this should likely be the default as it probably gives the best "works out of the box" experience.
=> Flip defaults

README.md, molecule/default/converge.yml, tasks/apps.yml
Fix for #46. 
I recently had to do this, where the yaml -> json internally -> back into yaml output was all thrown off. It  just didn't print it correctly on the other side, specifically the erb bit `"<%= '%02d:00:00' % hours %>"`.
```yaml
submit: |
---
script:
native:
- "-tl"
- "<%= '%02d:00:00' % hours %>"
- "-gcpit"
- "n1-standard-1"
```
=> add support for raw string submit instead of yaml

molecule/default/converge.yml, molecule/default/tests/test_custom.py, templates/env.j2
env uses double quotes to allow for bash variables so things like `$USER` get evaluated. Single quotes don't evaluate bash variables.
=> env uses double quotes to allow for bash variables

vars/RedHat-scl.yml
Adding the file RedHat-scl.yml is the easiest change I could find to allow this role to run on a RedHat host.
=> Include fails on RHEL without this file

.github/workflows/tests.yml, defaults/main.yml, handlers/main.yml, molecule/default/Dockerfile.j2, molecule/default/tests/conftest.py, molecule/default/tests/test_all.py, molecule/default/tests/test_custom.py, molecule/default/tests/test_default.py, tasks/deps.yml, tasks/install-rpm.yml, tasks/main.yml, vars/CentOS.yml, vars/RedHat-scl.yml, vars/RedHat.yml
Better support for centos/rhel 8. 
Along with 
- a bugfix for newer ansible versions that forces gpg checks on rpms
- refactor tests a little to have some helper functions
=> Support centos8

tasks/main.yml
If OOD role is defined along with other playbooks and a tag is used to
invoke non OOD related tasks, the OOD playbook will throw an error about
ansible_distribution not being defined.
This seems to be due the `tag: always` on include_vars tasks for ansible
specific distributions. This commits removes it.
=> Remove `tag: always` from include_vars

defaults/main.yml, tasks/apps.yml, tasks/clusters.yml, tasks/configure.yml, tasks/install-apps.yml, tasks/install-src.yml, tasks/passenger.yml
In a hardened server environment it is common to change the umask of the root user (and others) to a more restrictive setting such as '027' which remove default permissions from 'other'.  This breaks this role as many files that need to be read by other are not readable.  
To remediate I've done the following:  
- Set mode/mask any where a file/folder is copied, templated, downloaded, etc..
- Added a umask dictionary attribute to the app install from git functionality (defaults to '022')
- Reworded existing mode attributes to use the same easy to read format for permissions.
To note, when setting something to empty like 'o=' it will remove all permissions for 'o'.  Also, when using capital 'X' directories, binaries, and anything already executable will be made executable while everything …
=> ensure correct file permissions on file/folders and use same mode format

meta/main.yml
add namespace to galaxy metadata to fix warnings like
```text
WARNING  Computed fully qualified role name of open_ondemand does not follow current galaxy requirements.
Please edit meta/main.yml and assure we can correctly determine full role name:
galaxy_info:
role_name: my_name  # if absent directory name hosting role is used instead
namespace: my_galaxy_namespace  # if absent, author is used instead
```
=> add namespace to galaxy metadata

README.md, defaults/main.yml
default ood_source_version to working 1.8 tag which is currently `v1.8.20`. Also add a comment in the readme about how to change this default.
=> default ood_source_version to working 1.8 tag

defaults/main/.apps.yml, tasks/apps.yml
Minor added functionality to use ansible to handle initializers. As these files are rb code directly my general feeling is not to template these but rather handle those separately e.g. on some local git. And Ansible would just manage the deployment of OOD services and copy these rb-files over to the server side.
=> Added functionality to copy initializer rb-files with ansible

defaults/main/build.yml, molecule/default/prepare.yml, molecule/templates/prepare.yml, tasks/deps.yml
Ubuntu source installation needs the `bcrypt` gem and the RHEL tests are failing because of old certificates.
=> fix RHEL CI and Ubuntu src installation

defaults/main/.apps.yml, molecule/default/vars/apps.yml, tasks/configure.yml
This a workaround for  #54 , as the contents of the structure defined by `cluster` are only used in https://github.com/OSC/ood-ansible/blob/33feee0e93ee019a486512256bece11960aedfc0/tasks/configure.yml#L41-L47 we can just write the raw contents of the value from each defined cluster.
This method is also used in the  submit task for the apps https://github.com/OSC/ood-ansible/blob/33feee0e93ee019a486512256bece11960aedfc0/tasks/apps.yml#L22-L28
=> Potential workaround issue #54

defaults/main/ood_portal.yml, molecule/default/fixtures/config/ood_portal.yml.custom.apache2, molecule/default/fixtures/config/ood_portal.yml.custom.httpd, molecule/default/fixtures/config/ood_portal.yml.custom.httpd24-httpd, molecule/default/fixtures/config/ood_portal.yml.default.apache2, molecule/default/fixtures/config/ood_portal.yml.default.httpd, molecule/default/fixtures/config/ood_portal.yml.default.httpd24-httpd, molecule/default/fixtures/config/ood_portal.yml.oidc.apache2, molecule/default/fixtures/config/ood_portal.yml.oidc.httpd, molecule/default/fixtures/config/ood_portal.yml.oidc.httpd24-httpd, molecule/src-build/fixtures/config/ood_portal.yml.apache2, templates/ood_portal.yml.j2
Fixes #161 by adding `dex_uri` to ood_portal options.
=> add dex_uri to ood_portal options

CHANGELOG.md, tasks/install-package.yml
rm debian testing hack that used the `build` repo and update changelog for the next release.
=> rm debian testing hack and update changelog

defaults/main/install.yml, handlers/main.yml, tasks/configure.yml
Sometimes its useful to run this role without actually starting apache (e.g. for image build). Adds `apache_service_state` following the pattern for `apache_service_enabled`.
=> Add var apache_service_state

.config/ansible-lint.yml, handlers/main.yml, meta/main.yml, meta/requirements.yml, molecule/default/molecule.yml, molecule/default/prepare.yml, molecule/default/tasks/verify_custom.yml, molecule/default/tasks/verify_default.yml, molecule/default/verify.yml, molecule/upgrade/molecule.yml, molecule/upgrade/prepare.yml, molecule/upgrade/verify.yml, tasks/apps.yml, tasks/build.yml, tasks/configure.yml, tasks/deps.yml, tasks/install-apps.yml, tasks/install-package.yml, tasks/install-src.yml, tasks/main.yml, tasks/passenger.yml
Fixes #172 to fix all ansible-lint errors. The only remaining item is a single warning in our handler which will change in 2.1 anyhow when we remove building from the source.
=> fix linting errors and enable ansible-lint

defaults/main/ood_portal.yml, molecule/default/fixtures/config/ood_portal.yml.custom.apache2, molecule/default/fixtures/config/ood_portal.yml.custom.httpd, molecule/default/fixtures/config/ood_portal.yml.custom.httpd24-httpd, molecule/default/fixtures/config/ood_portal.yml.default.apache2, molecule/default/fixtures/config/ood_portal.yml.default.httpd, molecule/default/fixtures/config/ood_portal.yml.default.httpd24-httpd, molecule/default/fixtures/config/ood_portal.yml.oidc.apache2, molecule/default/fixtures/config/ood_portal.yml.oidc.httpd, molecule/default/fixtures/config/ood_portal.yml.oidc.httpd24-httpd, templates/ood_portal.yml.j2
Fixes #125. Note that whitelist is still available and will continue to work, but is not listed in defaults anymore.
=> change whitelist config to allowlist

molecule/requirements.txt
Fix molecule requirements for CI because there have been updates upstream. Namely to use `molecule-plugins` instead of the specific plugins.  We also have to lock ansible_compat because there's another bug I ran into.
=> fix molecule requirements for ci

molecule/default/fixtures/config/nginx_stage.yml.custom.Debian, molecule/default/fixtures/config/nginx_stage.yml.default.Debian, vars/Ubuntu/20.yml
The paths for nginx indicated in the variables file for Ubuntu 20 have not been adapted to the Ubuntu environment. They are in fact paths specific to the RedHat environment.
This PR corrects the paths for Ubuntu 20.
=> Fixes paths for nginx on Ubuntu 20

defaults/main/install.yml, tasks/install-package.yml
This works the same way it is set for the `state` of `ondemand_package`, allowing to either go for latest if no version is defined or to stay in the version that was defined otherwise.
=> Allow fixing the `ondemand-dex` package version avoiding auto updates issue #194

.github/workflows/tests.yml, defaults/main/.ondemand.yml, molecule/default/fixtures/ondemand.d/ondemand.yml, molecule/default/vars/ondemand.yml, vars/AlmaLinux/9.yml
Hi Team,
I added the `support_ticket` option to the corresponding template and example in the defaults. Tested this in my environment and it seems to work okay.
Results of my `ondemand.d/ondemand.yml` (trimmed the empty lines)
```yaml
pinned_apps_menu_length: 6
pinned_apps_group_by: ""
pinned_apps:
- sys/jupyter
- sys/rstudio
- sys/files
- sys/shell
- sys/bc_desktop/cluster
dashboard_layout:
rows:
- columns:
- widgets:
- motd
- pinned_apps
- recently_used_apps
width: 8
- widgets:
- xdmod_widget_job_efficiency
- xdmod_widget_jobs
width: 4
support_ticket:
attachments:
max_items: 4
max_size: 6291456
description: 'My optional description Text for the support ticket feture '
email:
delivery_method: smtp
delivery_settings:
address: <SMTP>
enable_starttls_auto: true
open_timeout: 15
port: 587 …
```
=> Add support_ticket option

vars/CentOS/9.yml
Created a copy from vars/RedHat/9.yml to vars/CentOS/9.yml. The repository has no out-of-the-box support for CentOS 9 without this. The distributions are similar enough that a simple copy works.
=> Created a copy from vars/RedHat/9.yml to vars/CentOS/9.yml

defaults/main/install.yml, tasks/install-package.yml
In some cases (for example when using a repo mirror) repo config files may already be present on the server and with this change makes it possible to skip tasks trying to modify existing configs.
=> Add parameter allowing to skip installation of repo config files

defaults/main/.ondemand.yml, molecule/default/fixtures/ondemand.d/ondemand.yml, templates/ondemand.yml.j2
Update the template to include support for the `help_menu` element.
Update defaults with an example taken from the official documentation.
=> Add support for `help_menu`

README.md, defaults/main/install.yml, molecule/upgrade/converge.yml, molecule/upgrade/vars/converge.yml, tasks/install-package.yml
The current defaults for `ondemand_package` and `ondemand_dex_package` aren't idempotent. This is problematic, as there is no way to get the behaviour of "install whatever the latest version is, then don't upgrade it on a rerun unless explicitly asked to". Note that *that* behaviour is the default yum/dnf behaviour.
This PR changes the behaviour of the defaults to be idempotent (hopefully that change is acceptable), and makes it so using `latest` is required to get an upgrade on an already-installed package.
The README changes have been made incorporating https://github.com/OSC/ood-ansible/pull/215
=> make ondemand and ondemand_dex package installs idempotent

.github/workflows/tests.yml, defaults/main/install.yml, molecule/default/molecule.yml, molecule/upgrade/molecule.yml, molecule/upgrade/prepare.yml, molecule/upgrade/vars/prepare.yml, molecule/upgrade/verify.yml, tasks/install-package.yml, vars/AlmaLinux/9.yml, vars/CentOS/8.yml, vars/RedHat/9.yml, vars/Rocky/9.yml
This fixes tests first, but then also updates defaults and logic to support 3.1.
=> update to 3.1

.github/workflows/publish.yml
This attempts to fix the publish to galaxy workflow that's currently failing with this error message:
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.12.2/x64/bin/ansible-galaxy", line 62, in <module>
import ansible.constants as C
File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/ansible/constants.py", line 15, in <module>
from ansible.config.manager import ConfigManager, ensure_type, get_ini_config_value
File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/ansible/config/manager.py", line 29, in <module>
from ansible.module_utils.six.moves import configparser
ModuleNotFoundError: No module named 'ansible.module_utils.six.moves'
```
=> fix galaxy publish 

.github/workflows/publish.yml
only install ansible-core and use python 3.x in an attempt to actually publish to ansible galaxy.
=> only install ansible-core and use python 3.x

tasks/install-package.yml
Current version of the role fails if you have `install_ondemand_dex` set to `true` as in https://github.com/OSC/ood-ansible/blob/2698b08951a8b4011d373253a06b9719f633109d/tasks/install-package.yml#L102 there is an non valid and undefined variable name `ondemand-dex` instead of `ondemand_dex_package`. 
In this case the role fails:
```
TASK [osc.open_ondemand : Install ondemand-dex] *****************************************************************************************************************************************************************************************************************************************
fatal: [ood-ubuntu-devel.scicore.unibas.ch]: FAILED! => 
msg: |-
The task includes an option with an undefined variable. The error was: 'ondemand' is undefined. 'ondemand' is …
```
=> Fix ondemand-dex package var name

defaults/main/install.yml, tasks/install-package.yml
We would like to use our internal mirror and this change allows to use custom urls instead of hardcoded ones
=> Also use a var when adding the node repo key

tasks/install-package.yml
The role is not idempotent because of this task that is executed on every run
Removing this task should make the role idempotent and should not affect the current behavior as the cache is anyway updated in the task installing the package in https://github.com/OSC/ood-ansible/blob/master/tasks/install-package.yml#L97
=> remove task updating apt cache on every execution

vars/RedHat/9.yml
Vars for RedHat 9 are missing quotes. 
This causes errors when using the role as Ansible cannot parse the YAML syntax.
=> Fix missing quotes in RedHat 9 vars

README.md, molecule/default/fixtures/ondemand.d/globus.yml, molecule/default/prepare.yml, molecule/default/tasks/verify_custom.yml, molecule/default/vars/ondemand.yml
=> add more tests for ondemand.d files

.github/workflows/tests.yml, vars/Ubuntu/24.yml
This pull request adds the variables for Ubuntu 24 to vars/Ubuntu/24.yml.
It is adapted from the Ubuntu 20 variables file. The only required change from previous Ubuntu versions is the ruby_lib_dir which changed to version 3.2. All package names are still the same.
I performed a successful OnDemand installation on Ubuntu 24 (noble) with the provided variables.
=> Provide variables for Ubuntu 24
