defaults/main.yml, tasks/install.yml
Update versions and copy paths to build 1.7.x versions.
=> Update to 1.7.x

.travis.yml, README.md, defaults/main.yml, handlers/main.yml, tasks/build.yml, tests/ansible.cfg, tests/check_syntax.sh, tests/docker/Dockerfile.debian, tests/docker/Dockerfile.fedora, tests/docker/Dockerfile.ubuntu, tests/inventory, tests/playbook.yml, tests/run_playbook.sh, tests/start_containers.sh, tests/utils.sh, vars/Debian.yml
This sets up a way to test this playbook in Travic CI.
Hopefully/maybe we'll setup a trigger on the main repo to build/test this so that it can automatically stay current with whatever going on in the main repo.
=> inital testing harness to run the playbook in Travis Ci

defaults/main.yml, molecule/default/playbook.yml, molecule/default/tests/test_custom.py, tasks/apps.yml, tasks/main.yml, templates/app.yml.j2, templates/env.j2
This commits enables customization of apps in /etc/ood/config/apps
directory. Creating yaml config files, env files and submit erb scripts
=> Add apps customization management

defaults/main.yml, molecule/default/playbook.yml, molecule/default/tests/test_custom.py, tasks/install-apps.yml, tasks/main.yml
Add support for a dict of repositories apps to be install
=> Install apps using git repository

molecule/default/playbook.yml, molecule/default/tests/test_custom.py, tasks/configure.yml, tasks/deps.yml, tasks/install-rpm.yml, templates/auth_openidc.conf.j2, vars/CentOS-scl.yml, vars/CentOS.yml, vars/Debian.yml, vars/Fedora.yml, vars/RedHat.yml, vars/Suse.yml, vars/Ubuntu.yml, vars/main.yml
Install apache mod_auth_openidc package when any of the oidc variables
are defined
=> Add openidc package when oidc_* is defined and mod_auth_openidc config for apache

molecule/default/playbook.yml, molecule/default/tests/test_custom.py, molecule/default/tests/test_instance.py, templates/ood_portal.yml.j2
Fix rnode_uri option using node_uri as a value
=> Fix rnode_uri config setting

README.md, defaults/main.yml
=> Add docs for apps, install_app and auth_oidc

README.md
Small documentation fixes from #44.
=> simple readme updates

tasks/configure.yml, tasks/deps.yml, tasks/main.yml, tasks/passenger.yml, templates/locations.ini.j2
Really this fixes #50 but also little bits that didn't work in Ubuntu like sudo/root usage.
=> Ubuntu fix

defaults/main.yml, tasks/deps.yml
Fix for Issue #61 . Referencing [geerlingguy/ansible-role-nodejs](https://github.com/geerlingguy/ansible-role-nodejs) for the install procedure. I also had to break out npm in to a separate line since the nodesource repository used packages npm with nodejs and trying to install it as well will try to install the one from Ubuntu's repository which is an incompatible version. I am pretty new to ansible so there may be a better way to write this if there are any suggestions.
=> install nodejs 10 from nodesource on Desbian

.gitignore, README.md, defaults/main.yml, tasks/install-rpm.yml, templates/nginx_stage.yml.j2, templates/ood-portal.conf.j2, templates/ood_portal.yml.j2
Updates to support 1.8 and dex.
=> Update to 1.8

molecule/templates/fixtures/ood-portal.conf.custom.httpd, molecule/templates/fixtures/ood-portal.conf.custom.httpd24-httpd, molecule/templates/fixtures/ood-portal.conf.default.httpd, molecule/templates/fixtures/ood-portal.conf.default.httpd24-httpd, templates/ood-portal.conf.j2
debian needs that extra newline in the template. Tried to outsmart myself and limit empty lines, but alas, Ubuntu isn't having any of it.
=> debian needs that extra newline in the template

.github/workflows/tests.yml
lock molecule and testinfra packages to ensure tests run correctly
=> lock molecule and testinfra packages to ensure tests run correctly

.github/workflows/tests.yml, molecule/README.md, molecule/requirements.txt
Bootstrap testing organisation
=> Add molecule README and requirements

.github/workflows/publish.yml, meta/main.yml
Fix #37 
- use the role open_ondemand instead of ood
- remove some unnessecary galaxy tags
- create a GH action for publishing on tags
=> galaxy updates

README.md
add version compatability note to the readme because we're about ready for the 1.8 tag and the release to galaxy.
=> add version compatability note to the readme

.github/workflows/publish.yml
galaxy may be case sensitive so this is to fix automatic galaxy imports.
=> galaxy may be case sensitive

CHANGELOG.md
add changelog and initialize it to 1.8.1
=> add changelog and initialize it to 1.8.1

.github/workflows/tests.yml
Add testing to the `develop` branch because I'm going to be working on that for a minute to keep master clean while I update to 2.0.
=> test the develop branch too

.github/workflows/tests.yml
actually we have to test release branches too
=> actually we have to test release branches too

defaults/main.yml, tasks/install-rpm.yml, vars/CentOS-scl.yml, vars/CentOS.yml, vars/RedHat-scl.yml, vars/RedHat.yml
This is the initial working version for 2.0 RPM installs. Note that it won't actually work because I need nginx_stage updates, so that's why I'm pulling into a `develop` branch while I work through the all the updates, then I'll sync that to master when it's ready.
=> Init 2.0 rpms

defaults/main.yml, tasks/deps.yml
update src build to match 2.0 dependencies and source code.
=> update src build to match 2.0

defaults/main.yml, molecule/default/fixtures/config/ood_portal.yml.custom.httpd, molecule/default/fixtures/config/ood_portal.yml.custom.httpd24-httpd, molecule/default/fixtures/config/ood_portal.yml.default.httpd, molecule/default/fixtures/config/ood_portal.yml.default.httpd24-httpd, molecule/default/vars/portal.yml, molecule/src-build/fixtures/config/ood_portal.yml.apache2, molecule/templates/fixtures/ood-portal.conf.custom.httpd, molecule/templates/fixtures/ood-portal.conf.custom.httpd24-httpd, molecule/templates/fixtures/ood-portal.conf.default.httpd, molecule/templates/fixtures/ood-portal.conf.default.httpd24-httpd, templates/ood-portal.conf.j2, templates/ood_portal.yml.j2
add user_map_match and change the cooresponding user_map_cmd defaults and comments.
Fixes #84.
=> add user_map_match

README.md, defaults/main/apps.yml, defaults/main/build.yml, defaults/main/install.yml, defaults/main/nginx_stage.yml, defaults/main/ondemand.yml, defaults/main/ood_portal.yml, molecule/default/verify.yml, molecule/src-build/verify.yml, molecule/templates/verify.yml
Fixes #104 . This may seem like it would break things, but it doesn't.  It's just a reshuffle of internal defaults.
=> break up giant defaults/main.yml into many files

tasks/configure.yml
Bugfix where ondemand.yml should be world readable.
=> ondemand.yml should be world readable

defaults/main/ood_portal.yml, molecule/default/fixtures/config/ood_portal.yml.custom.httpd, molecule/default/fixtures/config/ood_portal.yml.custom.httpd24-httpd, molecule/default/fixtures/config/ood_portal.yml.default.httpd, molecule/default/fixtures/config/ood_portal.yml.default.httpd24-httpd, molecule/default/vars/portal.yml, molecule/src-build/fixtures/config/ood_portal.yml.apache2, molecule/templates/fixtures/ood-portal.conf.custom.httpd, molecule/templates/fixtures/ood-portal.conf.custom.httpd24-httpd, molecule/templates/fixtures/ood-portal.conf.default.httpd, molecule/templates/fixtures/ood-portal.conf.default.httpd24-httpd, templates/ood-portal.conf.j2, templates/ood_portal.yml.j2
Add functionality for pun prehook.
=> add functionality for pun_pre_hook

templates/ood_portal.yml.j2
=> should check for pun_pre_hook_root_cmd not rnode_uri here

templates/ood-sudoers.j2
fixes #118 to update sudoers file for debians
=> update sudoers file for debians

molecule/default/Dockerfile.j2
update centos:8's mirror to use vault because centos:8 is EOL.
=> update centos:8's mirror

tasks/build.yml
add polling to long running deb build
=> add polling to long running deb build

molecule/requirements.txt
while testing this role locally I realized I was missing yamllint
=> add yamllint to molecule deps

defaults/main/nginx_stage.yml, molecule/default/fixtures/config/nginx_stage.yml.custom.Debian, molecule/default/fixtures/config/nginx_stage.yml.custom.RedHat, molecule/default/fixtures/config/nginx_stage.yml.default.Debian, molecule/default/fixtures/config/nginx_stage.yml.default.RedHat, molecule/default/vars/nginx.yml, molecule/src-build/fixtures/config/nginx_stage.yml, templates/nginx_stage.yml.j2
add addtional nginx_stage configs from 2.0 and fix a bug with `pun_custom_env`.
=> add addtional nginx_stage configs from 2.0

.github/workflows/tests.yml, molecule/upgrade/Dockerfile.j2, molecule/upgrade/converge.yml, molecule/upgrade/fixtures, molecule/upgrade/molecule.yml, molecule/upgrade/prepare.yml, molecule/upgrade/tasks, molecule/upgrade/vars/install.yml, molecule/upgrade/verify.yml
Add tests for upgrading from one version to another.
=> add tests for upgrading

defaults/main/build.yml, defaults/main/install.yml, molecule/upgrade/vars/prepare.yml, tasks/deps.yml, tasks/install-package.yml, vars/Ubuntu/20.yml
update apt_repo_url to point to newest deb package.
=> update apt_repo_url to point to new deb package

.github/workflows/tests.yml, handlers/main.yml, tasks/apps.yml, tasks/configure.yml, tasks/install-package.yml, vars/Debian.yml, vars/Ubuntu/18.yml, vars/Ubuntu/20.yml
=> Fix develop

.github/workflows/publish.yml, .github/workflows/tests.yml, defaults/main/install.yml, molecule/default/Dockerfile.j2, molecule/upgrade/vars/prepare.yml, vars/CentOS.yml, vars/RedHat.yml, vars/Rocky.yml, vars/Ubuntu/22.yml
=> support for 3.0

CHANGELOG.md, README.md
Update docs for next release. Note there are deprecations in the CHANGELOG.
=> update docs for next release

defaults/main/ood_portal.yml, molecule/default/fixtures/config/ood_portal.yml.custom.apache2, molecule/default/fixtures/config/ood_portal.yml.custom.httpd, molecule/default/fixtures/config/ood_portal.yml.custom.httpd24-httpd, molecule/default/fixtures/config/ood_portal.yml.default.apache2, molecule/default/fixtures/config/ood_portal.yml.default.httpd, molecule/default/fixtures/config/ood_portal.yml.default.httpd24-httpd, molecule/default/fixtures/config/ood_portal.yml.oidc.apache2, molecule/default/fixtures/config/ood_portal.yml.oidc.httpd, molecule/default/fixtures/config/ood_portal.yml.oidc.httpd24-httpd, templates/ood_portal.yml.j2
add support for server_aliases. Fixing #163
=> add support for server_aliases

molecule/default/fixtures/config/ood_portal.yml.custom.apache2, molecule/default/fixtures/config/ood_portal.yml.custom.httpd, molecule/default/fixtures/config/ood_portal.yml.custom.httpd24-httpd, molecule/default/vars/portal.yml, templates/ood_portal.yml.j2
correctly use server_aliases and update tests
=> correctly use server_aliases and update tests

meta/requirements.yml
=> remove dependencies

vars/AlmaLinux/8.yml
Duplicate of Rocky file
Successfully tested on Azure AlmaLinux 8.7
=> Support for AlmaLinux 8

.github/workflows/tests.yml, vars/AlmaLinux/9.yml
With #205  we can add tests for almalinux.
=> add tests for almalinux

molecule/requirements.txt
add podman to requirements.txt
=> add podman to requirements.txt

templates/auth_openidc.conf.j2
=> openidc config template to support complex configs

.github/workflows/publish.yml
add six to pip install so that publish may work again.
=> add six to pip install

.github/workflows/publish.yml
once again, trying to fix publish action though some of these updates just fix GH action deprecations.
=> once again, trying to fix publish action

defaults/main/ood_portal.yml, molecule/default/fixtures/config/ood_portal.yml.custom.apache2, molecule/default/fixtures/config/ood_portal.yml.custom.httpd, molecule/default/fixtures/config/ood_portal.yml.default.apache2, molecule/default/fixtures/config/ood_portal.yml.default.httpd, molecule/default/fixtures/config/ood_portal.yml.oidc.apache2, molecule/default/fixtures/config/ood_portal.yml.oidc.httpd, templates/ood_portal.yml.j2
Update `ood_portal.yml.j2` to support new 4.0 configurations.
=> 4.0 portal

defaults/main/install.yml
=> update to 4.0 repo

README.md, defaults/main/install.yml, handlers/main.yml, tasks/configure.yml
=> Dex handler
